sudo: required
language: python
python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"
  - "pypy"
#matrix:
#  include:
#    - python: 3.7
#      dist: xenial
#      sudo: required
env:
  global:
    - BOTO_CONFIG=/doesnotexist
install:
  - pip install coveralls
  - pip install tox==2.7.0
  - pip install tox-travis==0.8
script:
  - tox
after_success:
  - coveralls
  - bash <(curl -s https://codecov.io/bash)
