version: 2
jobs:
  build:
    working_directory: ~/creds
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          command: |
            python -m virtualenv venv
            . venv/bin/activate
            pip install coveralls
            pip install tox==2.7.0
            pip install tox-travis==0.8
            tox
